In [1]:
# Question 4: Convert categorical labels to one-hot encoded labels.
# Description: Use one-hot encoding for numerical stability during training.

In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Example categorical labels
labels = np.array(['cat', 'dog', 'bird', 'dog', 'cat']).reshape(-1, 1)

# Initialize OneHotEncoder (use sparse_output instead of sparse)
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the labels
one_hot_encoded = encoder.fit_transform(labels)

print("Original Labels:\n", labels.ravel())
print("One-Hot Encoded Labels:\n", one_hot_encoded)


Original Labels:
 ['cat' 'dog' 'bird' 'dog' 'cat']
One-Hot Encoded Labels:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
